import { Octokit } from 'octokit';
import eventBus from '../core/event-bus.js';

/**
 * AutoPR — Creates GitHub pull requests on task completion.
 * Implements GitHub issue #30.
 */
export class AutoPR {
  constructor({ gitManager, config = {} }) {
    this.git = gitManager;
    this.config = config;
    this.enabled = config.auto_pr !== false;
    this.baseBranch = config.base_branch || 'main';

    const token = config.github_token || process.env.GITHUB_TOKEN;
    this.octokit = token ? new Octokit({ auth: token }) : null;
    this._repoCache = null;
  }

  /**
   * Extract { owner, repo } from the git remote URL.
   * Handles both HTTPS and SSH formats.
   */
  parseRepo() {
    if (this._repoCache) return this._repoCache;
    const url = this.git.getRemoteUrl();
    // https://github.com/owner/repo.git  OR  git@github.com:owner/repo.git
    const match = url.match(/github\.com[:/]([^/]+)\/([^/.]+)/);
    if (!match) throw new Error(`Cannot parse GitHub repo from URL: ${url}`);
    this._repoCache = { owner: match[1], repo: match[2] };
    return this._repoCache;
  }

  /**
   * Create a PR for the given branch/task.
   * @param {string} branchName - Head branch
   * @param {Object} task - Completed task
   * @param {Object} [agent] - Agent config
   * @returns {Promise<Object|null>} PR data or null if disabled/not configured
   */
  async createPR(branchName, task, agent = {}) {
    if (!this.enabled || !this.octokit) return null;

    const { owner, repo } = this.parseRepo();
    const title = `[AgentForge] ${task.title}`.slice(0, 256);

    const body = [
      `## Task`,
      `| Field | Value |`,
      `|-------|-------|`,
      `| **ID** | \`${task.id}\` |`,
      `| **Type** | ${task.type || '-'} |`,
      `| **Agent** | ${agent.name || task.agent_id || '-'} |`,
      `| **Model** | \`${task.model_used || '-'}\` |`,
      `| **Cost** | $${(task.cost || 0).toFixed(4)} |`,
      `| **Tokens** | ${task.tokens_in || 0} in / ${task.tokens_out || 0} out |`,
      ``,
      `## Summary`,
      task.result ? String(task.result).slice(0, 1000) : '_No result_',
      ``,
      `---`,
      `*Auto-generated by [AgentForge](https://github.com/agentforge/agentforge)*`,
    ].join('\n');

    const pr = await this.octokit.rest.pulls.create({
      owner,
      repo,
      title,
      body,
      head: branchName,
      base: this.baseBranch,
    });

    const prData = {
      number: pr.data.number,
      url: pr.data.html_url,
      branch: branchName,
      task_id: task.id,
    };

    eventBus.emit('git.pr_created', prData);
    console.log('[auto-pr] Created PR #%d: %s', pr.data.number, pr.data.html_url);

    return pr.data;
  }
}

export default AutoPR;
